### ISSUE TITLE
Add Max Line Length to Formatter

### ISSUE THREAD

**Issue by gbritton1** [DotJoshJohnson/vscode-xml#126]
I notice that the default indentation on reformatting XML appears to be 8 characters.  Can that be changed?  Usually I prefer 4 characters, but ideally it would be configurable.  Same thing with max line length (is there one?)

**Comment by Ebuall** [comment]
Not sure if this fixed, but looks like indentation reads editor configurations for file. 
But splitting parameters on new line option works only after exceeding some line length. And this line length is indeed to high — more than 153, which is almost twice of desired value.

**Comment by DotJoshJohnson** [comment]
The extension does currently use the editor settings for indentation size and type. As far as max line length goes, that behavior is undefined. I will take this into consideration during the rewrite (PR #141).

**Comment by DotJoshJohnson** [comment]
I will not have time to work on this in the near future. I will accept PRs for the feature after `v2.0.0` is released.

**Comment by DotJoshJohnson** [comment]
@gbritton1 - What would the desired behavior be when the max line length is reached? Start splitting attributes onto the next line as if the `splitAttributes` setting were enabled, or did you have something else in mind?

**Comment by gbritton1** [comment]
I'd start with the simplest option, then get fancy as feedback comes in. Splitting on an attribute would be good. So would splitting the text between the tags e.g. on a space.

**Comment by DotJoshJohnson** [comment]
Upon additional thought, I am leaning toward not implementing this feature. The consensus thus far has been to keep XML data intact as much as possible and treat anything to the contrary as a bug. If I split lines on spaces, for example, instead of in between attributes, I'm effectively changing the content/data of the XML document, which reaches beyond formatting and would actually break at least one of our unit tests. At that point, if all we are doing is splitting on attributes, enabling the `splitAttributes` setting will accomplish the same thing anyway.
