### ISSUE TITLE
I met a problem

### ISSUE THREAD

**Issue by xin2017338** [DotJoshJohnson/vscode-xml#158]
Running the contributed command:'xmlTools.formatAsXml' failed.
I don't know how to solve it

**Comment by DotJoshJohnson** [comment]
Please provide the following information:

* Operating System
* VS Code Version
* XML Tools Version
* An XML file or snippet that can be used to reproduce the error.

**Comment by roberto-mardeni** [comment]
This has to do with an invalid XML document being formatted and not reporting what the problem is. I verified this by removing this extension and using a different one that actually reported the problem correctly. It's a shame that this extension that used to do a great job it is not doing so anymore. Changing the setting "xmlTools.xmlFormatterImplementation" to "classic" does not help either.

**Comment by DotJoshJohnson** [comment]
@roberto-mardeni - The [previous formatter implementation](https://github.com/DotJoshJohnson/vscode-xml/blob/v1.9.2/src/services/XmlFormatter.ts) (classic) used regex to reason about the file and the [new implementation](https://github.com/DotJoshJohnson/vscode-xml/blob/v2.2.0/src/formatting/formatters/v2-xml-formatter.ts) (v2) loops over each character individually. Neither implementation ever used an actual XML parser and thus could never have provided feedback on poorly-formed XML.

I can certainly add a feature that would attempt to parse the XML using `xmldom` and report back any errors if that would be helpful.

Thanks for the feedback!

**Comment by xin2017338** [comment]
OK,get  it

**Comment by DotJoshJohnson** [comment]
Closing in favor of the aforementioned enhancement.
