### ISSUE TITLE
Replace the Tree View by the new Outline

### ISSUE THREAD

**Issue by mxschmitt** [DotJoshJohnson/vscode-xml#191]
Replace the tree view in the sidebar by the new outline.

Some API features are maybe already integrated: https://github.com/Microsoft/vscode/issues/34968
And it's already integrated in the VS Code insiders version.

Example screenshot:

![image](https://user-images.githubusercontent.com/17984549/41144314-d0dbb6fa-6afc-11e8-9f7a-e9c6ddd7dfbb.png)

**Comment by DotJoshJohnson** [comment]
I have no plans to add this in the near future as it would require me to add symbol information support to XML documents. Also, we'd actually lose some functionality by moving to the outline view (custom commands/cursor sync and custom icons). The code outline is better suited for actual code rather than markup such as XML.
