### ISSUE TITLE
4 different XML files, two different indentations

### ISSUE THREAD

**Issue by JosephmLin** [DotJoshJohnson/vscode-xml#195]
#### Description
What seems to be the problem?
I have 4 different XML files. For three of the files, the indentation is 4 spaces. Only one of the files formats to two spaces.

I'm not sure if this is another extension messing with the formatter, or if it's just the formatter itself. 

In my workspace settings, I try to specify the formatter to use 2 spaces instead of 4.
Workspace Settings:
{
  "java.configuration.updateBuildConfiguration": "automatic",
  "prettier.tabWidth": 2,
  "[yaml]": {
    "editor.insertSpaces": true,
    "editor.tabSize": 2,
    "editor.autoIndent": false
  },
  "editor.tabSize": 2,
  "xmlTools.enforcePrettySelfClosingTagOnFormat": true
}

#### Formatter Implementation
v2

#### XML Tools Version
2.2.0

#### VS Code Version
1.24.0

#### Operating System
Windows 10

**Comment by ghost** [comment]
stop

发自我的 iPhone

在 2018年6月11日，23:19，Joseph Lin <notifications@github.com<mailto:notifications@github.com>> 写道：

Description

What seems to be the problem?
I have 4 different XML files. When I try to format them, the indentation is 4 spaces. Only one of the files formats to two spaces, while the other files have 4 spaces.

I'm not sure if this is another extension messing with the formatter, or if it's just the formatter itself.

In my workspace settings, I try to specify the formatter to use 2 spaces instead of 4.
Workspace Settings:
{
"java.configuration.updateBuildConfiguration": "automatic",
"prettier.tabWidth": 2,
"[yaml]": {
"editor.insertSpaces": true,
"editor.tabSize": 2,
"editor.autoIndent": false
},
"editor.tabSize": 2,
"xmlTools.enforcePrettySelfClosingTagOnFormat": true
}

Formatter Implementation

v2

XML Tools Version

2.2.0

VS Code Version

1.24.0

Operating System

Windows 10

**Comment by DotJoshJohnson** [comment]
@JosephmLin - Can you check your `editor.detectIndentation` setting? If it is set to `true`, please try setting it to `false` and retry formatting. The formatter just uses the tab width provided by the editor and sometimes it can detect the "wrong" size, especially if the XML is particularly messy.

**Comment by DotJoshJohnson** [comment]
Pushed to the next feature release.

**Comment by Ceaus** [comment]
I ran into the same issue. As suggested I've set `editor.detectIndentation` to `False`, which has solved the issue. The indentation is now consistent.
