### ISSUE TITLE
Attributes hardly visible in tree view with dark themes

### ISSUE THREAD

**Issue by mad-mike** [DotJoshJohnson/vscode-xml#48]
Consider the following XML fragment

``` XML
<foo bar="test"/>
```

which the XML Tree View displays like this in VS Code's Dark+ theme:

![image](https://cloud.githubusercontent.com/assets/1785184/13529265/93a6de98-e21b-11e5-8b49-4ca79e5f5f9c.png)

I can hardly decipher the attribute. Changing the theme to change the background color does help, but this can only be a workaround.

**Comment by DotJoshJohnson** [comment]
This one will be a little tricky to do "properly" . VS Code doesn't officially support a custom UI - we are using the HTML preview feature to show the XML tree. There are a few ways we can potentially handle this. I'm listing them here in order of what I intend to research and try first. In the worst-case scenario, we will hard-code the XML Tree background until an official API is exposed.
- ~~Use the `localStorage` API to determine the current theme.~~
- ~~Use the global `Memento` to determine the current theme (`workbench.theme`).~~
- Locate and read `storage.json` in a platform-independent manner to determine the current theme.
- Expose a setting for users to manually control the text color in the XML tree.
- Hard-code the background-color of the tree to `#FFFFFF`.

**Comment by mad-mike** [comment]
Actually, there's even option 6:
- Choose text colors that work on most backgrounds (i.e. gray works in light and dark themes, as you can see in the screen shot).

I've tested that in my fork, but even I see that at the very bottom of the list.

**Comment by DotJoshJohnson** [comment]
The fix for this has been released in [v1.5.1](https://github.com/TrueCommerce/vscode-xml/releases/tag/v1.5.1). We'll first try to read `storage.json` to determine if the theme is categorized as dark or light. Otherwise, the font color will be defaulted to `#AAAAAA`. Take note that `storage.json` is only updated as VS Code is closing. Thus, anytime a theme is changed from light to dark (or vice versa), VS Code must be restarted before the XML Tree View is updated.
