### ISSUE TITLE
Copy xpath of current element in xml doc - FR

### ISSUE THREAD

**Issue by jgstew** [DotJoshJohnson/vscode-xml#85]
**Feature Request:**

Is there currently an option to copy the current xpath of a selected element within an open XML doc?

I use this function all the time in some other editors and am trying to get the same functionality to work within VS Code. I've installed this extension but it doesn't seem to do that. If possible, I'd like to see this functionality added.

-----------------

There is an extension that provides this functionality to Visual Studio (not VS Code) here:

- https://marketplace.visualstudio.com/items?itemName=UliWeltersbach.XPathInformation
- https://github.com/uli-weltersbach/XPathInformation

Notepad++ extension:

- https://github.com/morbac/xmltools
- http://www.herongyang.com/XML/NPP-XML-Tools-Plugin-for-Notepad-Plus-Plus.html
- https://sourceforge.net/projects/npp-plugins/files/XML%20Tools/Xml%20Tools%202.4.8%20Unicode/
- https://notepad-plus-plus.org/community/topic/12556/xml-tools-2-4-9-x64-released-for-tests
- https://notepad-plus-plus.org/community/topic/11478/installation-of-xml-tools-failed
 - https://notepad-plus-plus.org/community/topic/12187/xml-tools-plugin-request

**Comment by DotJoshJohnson** [comment]
Thanks for the suggestion! This is a feature I've been wanting to add, I just haven't had the time recently to do it. I'm hoping to pick this project back up again in a week or two, so perhaps I can squeeze this one in.

**Comment by MrLesh** [comment]
Hi Josh,
Is that implemented already? I was looking for the exact same thing...

**Comment by DotJoshJohnson** [comment]
@MrLesh, no I unfortunately haven't had time yet to revisit this extension. If anyone gets to it before me and wants to submit a PR, I'm more than happy to merge it in! :)

**Comment by cori** [comment]
As an alternative or addition to this enhancement, it would be handy to show the xpath to the currently selected node in the status bar (or somewhere else)

**Comment by MetalBlueberry** [comment]
I need this too!!

**Comment by jleclanche** [comment]
@cori +1 on showing the xpath in the status bar! the extension JSONPath StatusBar (`richie5um2.vscode-statusbar-json-path`) does exactly that for JSON, it'd be really cool to have that here too.

**Comment by DotJoshJohnson** [comment]
This will be in the next release, albeit in an "experimental" state. Please feel free to beat up the feature a bit and report back any bugs. Thanks!

**Comment by Teodor-Tenev** [comment]
Great work, but I still can't get the correct xPath. When extracting I receive /AppiumAUT/XCUIElementTypeApplication/XCUIElementTypeWindow[10] instead of /AppiumAUT/XCUIElementTypeApplication/XCUIElementTypeWindow[1]

**Comment by DotJoshJohnson** [comment]
Hi, @phoenixcat - Can you submit a new issue with a copy of the XML that you're having trouble with? Thanks!

**Comment by RokeJulianLockhart** [comment]
> [`#issuecomment-393002646`](https://github.com/DotJoshJohnson/vscode-xml/issues/85#issuecomment-393002646)

@DotJoshJohnson, how does one do so? I don't see a tree where I could generate an XPath from. I ask because what [`wiki/XML-Tree-View/3d6d7bddceaa8978e48a5d0976a4028a1c5dad97`](https://github.com/DotJoshJohnson/vscode-xml/wiki/XML-Tree-View/3d6d7bddceaa8978e48a5d0976a4028a1c5dad97#:~:text=XML%20Tools:%20View%20XML%20Tree) describes doesn't exist with `v2.5.1` in `code-1.105.1-1760482588.el8`:

[^1]: [`bugs.kde.org/show_bug.cgi?id=511477#c1`](https://bugs.kde.org/show_bug.cgi?id=511477#c1:~:text=2025%2D11%2D03%2021:06:27%20GMT-,Duplicates%20https://bugs.kde.org/show_bug.cgi?id=510982%23c2.,-***%20This%20bug)

<p></p><img width="1407" height="487" alt="Image" src="https://github.com/user-attachments/assets/de82dabe-a2c4-4b43-964a-b35b676e49a8" /><p></p>

[^1]
