### ISSUE TITLE
Make filetypes configurable

### ISSUE THREAD

**Issue by boguscoder** [DotJoshJohnson/vscode-xml#91]
IIRC list of file name extensions where plugin is enabled is hardcoded right now (xml, xsl..)
It would be great to make it configurable so that users can apply ad-hoc formatting in the files of their interest. 
Good example is logfiles (*.log) that have xml among other data, its not feasible to change their type to xml on the fly because it would disable precious log formatters and also would probably just kill xml formatter if tried on big file, but applying formatting from context menu/hotkey to a single logline would be golden

I can draft a PR if you accept contributions

**Comment by DotJoshJohnson** [comment]
@boguscoder, I'd be happy to merge a PR to get this feature in your hands. When I finally get the time to revisit this extension, I plan on making some pretty big rewrites to bring everything up-to-date and resolve some of the open issues. I'll be sure to bring your changes along for the ride then as well.

**Comment by mattdkerr** [comment]
Would love this feature, lots of XML files in C# development have other file extensions (.csproj, .cscfg, .csdef, .proj, .props, .properties, etc)

**Comment by boguscoder** [comment]
so far it seems that list of 'activation' file types is hardcoded in extension static configuration, unless I missed smth obvious. In that case I dont see anything better than enabling it for all file types, which maybe arguable?..

**Comment by mattdkerr** [comment]
If you enable for all types then have a default internal config in the vscode-xml extension, of the right filename extensions, then have user overrides in their config folder?

**Comment by boguscoder** [comment]
user can't override extension properties,  the part in package.json that triggers activation, a la "activationEvents": [
		"onLanguage:xml"

**Comment by boguscoder** [comment]
I may try [activation](https://code.visualstudio.com/docs/extensionAPI/activation-events) by command

**Comment by DotJoshJohnson** [comment]
In the past, I had toyed with the idea of activating the extension on all file types and putting logic in place that "detected" when a file or selection was XML. This would expand the goal of this issue across the entire feature set and not just formatting.

**Pro**: No hard-coded or manual maintenance of file extensions. Any file can leverage any feature the extension contributes.

**Con**: Once the extension is activated, the commands and features it contributes are made available to the user. For example, if the user opens a CSV file and we activate, they'll have the option to minify XML. Even with the "XML detection" logic in place, the contributed commands are still available in the command palette. We can throw a warning or error in the case a user tries to run XPath on a CSV file, but it just seemed less clean.

Now, the API has changed a bit since I last made changes to the extension. There may be a way now to dynamically show/hide commands in code. But as of the last time I worked on things, that wasn't possible.

However, with the above said, we may find that there is simply more value in having the extension activate immediately despite the UX drawbacks. If that is the case, I'm open to that solution.

**Comment by boguscoder** [comment]
I personally would not mind having always present/global command a la 'Try formatting as XML'. 
I can see that you have some leftovers of xmlTools.formatXml command in sources but its not implemented.
This is extra to formatting service that you already have

**Comment by DotJoshJohnson** [comment]
The "Format as XML" command will be added in the next release and is being tracked in issue #97. This will allow you to format any XML snippet, regardless of what language is selected.
