### ISSUE TITLE
Unable to format 14Mb document - no command

### ISSUE THREAD

**Issue by xumix** [DotJoshJohnson/vscode-xml#95]
Here is the sample file:
[13388769_Принтеры, сканеры, МФУ.zip](https://github.com/DotJoshJohnson/vscode-xml/files/917146/13388769_.zip)

**Comment by sumeragigyou** [comment]
"Fomatting" doesn't work on the large XML file approx. 180,000+ lines (15.8 MB).

- VS Code: 1.11.2
- XML Tools: 1.7.0
- Windows 10 (10.0.14393 x64)

Thanks!

**Comment by martinscholz83** [comment]
I can confirm this behavior. If you open a large file you can't format your code.

**Comment by DotJoshJohnson** [comment]
I simply hook into the "Format" command provided by the editor, so I have no control over whether or not that command is available. With that said, in the next build, I will be adding a "Format as XML" command to the palette, which should ALWAYS be available. This will not fix any issues that arise due to Code struggling with the large file (the missing Format command is an indication of large file issues in Code), but it will at least allow you to try formatting whatever you have open, regardless of Code's current state.

**Comment by DotJoshJohnson** [comment]
The new "Format as XML" command will be tracked by issue #97. This command will also support formatting a selection (in case you are unable to format the entire document due to its size).
